sonar.projectKey=AngelPuentesDevv_SciCalc-Pro
sonar.projectName=SciCalc Pro
sonar.projectVersion=1.0.0
sonar.organization=angelpuentesdevv

sonar.sources=backend/src
sonar.tests=backend/tests
sonar.language=py
sonar.sourceEncoding=UTF-8

sonar.python.coverage.reportPaths=backend/coverage.xml
sonar.python.version=3.12

sonar.exclusions=**/migrations/**,**/__pycache__/**,**/*.pyc

sonar.qualitygate.wait=true
